import React, { useEffect, useState } from 'react';
import { Download } from 'lucide-react';
import { feedbackService } from '@services/api.service';

const AdminFeedback = () => {
	const [rows, setRows] = useState([]); const [minRating, setMinRating] = useState('');
	const load = () => feedbackService.list({ min_rating: minRating || undefined }).then((result) => setRows(result.data || []));
	useEffect(() => { load(); }, []);
	const average = rows.length ? rows.reduce((sum, row) => sum + row.average_rating, 0) / rows.length : 0;
	const download = async () => { const blob = await feedbackService.export({ min_rating: minRating || undefined }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'feedback.csv'; anchor.click(); URL.revokeObjectURL(url); };
	return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-on-surface">Feedback viewer</h1></div><button type="button" onClick={download} className="inline-flex items-center gap-2 rounded-xl border border-surface-variant/40 bg-surface-container-low px-4 py-2.5 text-sm font-semibold"><Download size={17} /> Export CSV</button></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-surface-container-low p-5 shadow-panel"><p className="text-sm text-on-surface-variant">Submissions</p><p className="mt-2 text-3xl font-semibold">{rows.length}</p></div><div className="rounded-2xl bg-surface-container-low p-5 shadow-panel"><p className="text-sm text-on-surface-variant">Average rating</p><p className="mt-2 text-3xl font-semibold">{average.toFixed(2)}</p></div><div className="rounded-2xl bg-surface-container-low p-5 shadow-panel"><label className="text-sm text-on-surface-variant">Minimum rating</label><select value={minRating} onChange={(event) => { setMinRating(event.target.value); setTimeout(load, 0); }} className="mt-2 w-full rounded-lg border border-surface-variant/40 px-3 py-2"><option value="">All</option><option value="3">3+</option><option value="4">4+</option><option value="5">5</option></select></div></div><div className="overflow-x-auto rounded-2xl border border-surface-variant/40 bg-surface-container-low shadow-panel"><table className="w-full text-left text-sm"><thead className="border-b bg-surface-container text-xs uppercase tracking-wide text-on-surface-variant"><tr><th className="p-4">Student ID</th><th className="p-4">Department</th><th className="p-4">Week</th><th className="p-4">Rating</th><th className="p-4">Comments</th></tr></thead><tbody>{rows.map((row) => <tr key={row._id} className="border-b last:border-0"><td className="p-4">{row.student?._id || 'Hidden for HOD'}</td><td className="p-4">{row.department}</td><td className="p-4">{row.week_number}</td><td className="p-4 font-semibold">{row.average_rating.toFixed(2)}</td><td className="p-4 text-on-surface-variant">{row.comments || '-'}</td></tr>)}</tbody></table></div></section>;
};
export default AdminFeedback;
