import { useEffect, useState } from 'react';
import { facultyService } from '@services/api.service';

export default function ProfileChangeRequests() {
  const [requests, setRequests] = useState([]);
  const [message, setMessage] = useState('');
  const load = () => facultyService.getProfileChangeRequests().then((result) => setRequests(result.data || [])).catch(() => setMessage('Unable to load profile requests.'));
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  const review = async (id, action) => { try { await facultyService.reviewProfileChangeRequest(id, { action }); setMessage(action === 'escalate' ? 'Request escalated to the HOD.' : `Request ${action}d.`); load(); } catch (error) { setMessage(error.response?.data?.message || 'Unable to review request.'); } };
  return <section className="space-y-6"><header><h1 className="text-3xl font-bold text-on-surface">Profile change requests</h1><p className="mt-2 text-sm text-on-surface-variant">Student requests start here. Escalate exceptional cases to the HOD.</p></header>{message && <p className="rounded-lg bg-primary/10 p-3 text-sm text-primary">{message}</p>}<div className="space-y-3">{requests.length === 0 && <p className="rounded-xl border border-surface-variant/40 p-5 text-sm text-on-surface-variant">No requests are waiting for your department.</p>}{requests.map((request) => <article key={request._id} className="rounded-xl border border-surface-variant/40 bg-surface-container-low p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold text-on-surface">{request.student?.name || 'Student'}</h2><p className="text-xs text-on-surface-variant">{request.student?.email} · {request.change_field}</p></div><span className="text-xs uppercase text-primary">{request.status}</span></div><p className="mt-4 text-sm text-on-surface-variant"><strong>Requested:</strong> {request.proposed_value}</p><p className="mt-1 text-sm text-on-surface-variant"><strong>Reason:</strong> {request.reason}</p>{['pending_faculty', 'pending'].includes(request.status) && <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => review(request._id, 'approve')} className="rounded-md bg-primary px-3 py-2 text-xs font-semibold text-slate-950">Approve</button><button onClick={() => review(request._id, 'reject')} className="rounded-md border border-surface-variant/50 px-3 py-2 text-xs font-semibold text-on-surface">Reject</button><button onClick={() => review(request._id, 'escalate')} className="rounded-md border border-amber-300/40 px-3 py-2 text-xs font-semibold text-amber-200">Escalate to HOD</button></div>}</article>)}</div></section>;
}
