import { useEffect, useState } from 'react';
import { ShieldCheck, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '@hooks/useAuth';
import { adminService, facultyService, hierarchyService } from '@services/api.service';

export default function AccountSettings() {
  const { user, setUser } = useAuth();
  const role = user?.role || 'user';
  const isRequester = role === 'faculty' || role === 'hod';
  const [request, setRequest] = useState({ change_field: 'name', proposed_value: '', reason: '' });
  const [requests, setRequests] = useState([]);
  const [adminForm, setAdminForm] = useState({ name: user?.name || '', email: user?.email || '', department: user?.department || user?.dept || '' });
  const [message, setMessage] = useState('');

  const loadRequests = () => (role === 'faculty' ? facultyService.getProfileChangeRequests() : hierarchyService.getHodProfileRequests({ mine: 'true' })).then((result) => setRequests((result.data || []).filter((item) => item.requester_role === role))).catch(() => {});
  useEffect(() => { if (!isRequester) return undefined; loadRequests(); const timer = setInterval(loadRequests, 30000); return () => clearInterval(timer); }, [role]);
  const pending = requests.find((item) => ['pending_hod', 'pending_admin'].includes(item.status));
  const submit = async (event) => { event.preventDefault(); try { const result = role === 'faculty' ? await facultyService.createProfileChangeRequest(request) : await hierarchyService.createHodProfileRequest(request); setRequests((current) => [result.data, ...current]); setRequest({ ...request, proposed_value: '', reason: '' }); setMessage(result.message || 'Settings request submitted.'); } catch (error) { setMessage(error.response?.data?.message || 'Unable to send settings request.'); } };
  const saveAdminSettings = async (event) => { event.preventDefault(); const userId = user?._id || user?.id || user?.userId; if (!userId) { setMessage('Your session does not contain a user ID. Please sign in again.'); return; } try { const result = await adminService.updateUser(userId, adminForm); const savedUser = { ...user, ...(result.data || adminForm), userId }; setUser(savedUser); localStorage.setItem('ai_buddy_user', JSON.stringify(savedUser)); setAdminForm({ name: savedUser.name || '', email: savedUser.email || '', department: savedUser.department || '' }); setMessage('Admin settings updated and saved.'); } catch (error) { setMessage(error.response?.data?.message || 'Unable to update admin settings.'); } };

  return <section className="mx-auto max-w-3xl space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Account</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-on-surface">Settings</h1><p className="mt-2 text-sm text-on-surface-variant">Review and update your account details.</p></header>
    <section className="rounded-2xl border border-surface-variant/40 bg-surface-container-low p-6 shadow-panel">
      <div className="flex items-center gap-3 border-b border-surface-variant/30 pb-5"><div className="grid h-12 w-12 place-items-center rounded-full bg-primary/15 text-primary"><UserRound size={23} /></div><div><h2 className="font-semibold text-on-surface">Personal information</h2><p className="text-sm text-on-surface-variant">Details maintained by your institution</p></div></div>
      {role === 'admin' ? <form onSubmit={saveAdminSettings} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-on-surface">Full name<input required value={adminForm.name} onChange={(event) => setAdminForm({ ...adminForm, name: event.target.value })} className="mt-2 w-full rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 font-normal" /></label><label className="text-sm font-semibold text-on-surface">Email<input required type="email" value={adminForm.email} onChange={(event) => setAdminForm({ ...adminForm, email: event.target.value })} className="mt-2 w-full rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 font-normal" /></label><label className="text-sm font-semibold text-on-surface">Department<input required value={adminForm.department} onChange={(event) => setAdminForm({ ...adminForm, department: event.target.value })} className="mt-2 w-full rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 font-normal" /></label><div className="flex items-end"><button className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-slate-950">Save admin settings</button></div></form> : <div className="mt-6 grid gap-5 sm:grid-cols-2">{[['Full name', user?.name], ['Email', user?.email], ['Role', role], ['Department', user?.department || user?.dept]].map(([label, value]) => <div key={label}><p className="mb-2 text-sm font-semibold text-on-surface">{label}</p><p className="rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 text-sm capitalize text-on-surface">{value || 'Not provided'}</p></div>)}</div>}
    </section>
    {isRequester && <form onSubmit={submit} className="rounded-2xl border border-surface-variant/40 bg-surface-container-low p-6 shadow-panel"><h2 className="font-semibold text-on-surface">Request a settings change</h2><p className="mt-1 text-sm text-on-surface-variant">{role === 'hod' ? 'HOD requests go directly to Admin for final review.' : 'Faculty requests go directly to the HOD for review.'}</p><div className="mt-4 grid gap-3"><select value={request.change_field} onChange={(event) => setRequest({ ...request, change_field: event.target.value })} className="rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 text-sm"><option value="name">Full name</option><option value="email">Email</option><option value="department">Department</option></select><input required value={request.proposed_value} onChange={(event) => setRequest({ ...request, proposed_value: event.target.value })} placeholder="Requested value" className="rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 text-sm" /><textarea required value={request.reason} onChange={(event) => setRequest({ ...request, reason: event.target.value })} placeholder="Reason for this change" className="min-h-24 rounded-lg border border-surface-variant/40 bg-surface-container px-3 py-2.5 text-sm" /><button disabled={Boolean(pending)} className="w-fit rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">{pending ? `Request is ${pending.status.replace('_', ' ')}` : `Send request to ${role === 'hod' ? 'Admin' : 'HOD'}`}</button>{message && <p className="text-sm text-primary">{message}</p>}</div></form>}
    {role === 'admin' && <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-start gap-3"><ShieldCheck className="text-primary" size={20} /><div><h2 className="font-semibold text-on-surface">Admin controls</h2><p className="mt-1 text-sm text-on-surface-variant">Admins can directly manage institutional user details.</p><Link to="/admin/users" className="mt-3 inline-flex rounded-md bg-primary px-3 py-2 text-sm font-semibold text-slate-950">Manage user details</Link></div></div></section>}
  </section>;
}
